package br.gov.mg.probpms.demand.domain;

public enum DemandStatus {
  NEW, ANALYSIS, WAITING_INFORMATION, PLANNED, IN_DEVELOPMENT,
  TESTING, HOMOLOGATION, READY_TO_PUBLISH, PUBLISHED, COMPLETED, CANCELLED, REJECTED
}
